### PR TITLE
Changed from 8-Bit to 2_bit outputs.

### PR DESCRIPTION
**Pull request by rmh10**
Changed the output of the Address_Select and the Register_Select files to 2-bit numbers as suggested in the project description.

### CODE REVIEW

**Review by FueledbyJordan — COMMENTED** [review]
not yet

**Review by jwhumphries — COMMENTED** [review]
Looks good

**Comment by jwhumphries** [comment]
Merge this

**Comment by rmh10** [comment]
Yes, I agree with this pull request as well.

**Pull request merged**
